[package]
name = "par_proj"
version = "0.1.0"
authors = ["nico"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
participant_lib = {path = "particle"}
termion = "*"